
  name: AndroidBuilds
  on:
    pull_request:
      branches: [master]
    push:
      branches: [master]
  jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.7
          - name: Setup Java JDK
            uses: actions/setup-java@v4.2.2
            with:
              java-version: "17"
              distribution: "adopt"
          - name: Grant execute permission to Gradle wrapper
            run: chmod +x ./gradlew
          - name: Build with gradle
            run: ./gradlew build
          - name: Download a Build Artifact
            uses: actions/upload-artifact@v3.1.3
            with:
              name: Androidapk.apk
              path: app/build/outputs/apk/debug/app_debug.apk